version: '3'
services:
  api-local:
    profiles: ['local']
    env_file:
    - docker/local.env
    build: .
    ports:
    - 9092:9092
    command: localapi

  socket-local:
    profiles: ['local']
    env_file:
    - docker/local.env
    build: .
    ports:
    - 8444:8444
    command: localsocket

  api-server:
    profiles: ['server']
    env_file:
    - docker/server.env
    build: .
    ports:
    - 9092:9092
    command: serverapi

  socket-server:
    profiles: ['server']
    env_file:
    - docker/server.env
    build: .
    ports:
    - 8444:8444
    command: serversocket