## 用于docker-compose部署启动官方镜像

version: '3'
services:

  ## http
  api-http:
    profiles: ['http']
    container_name: api
    image: iamtsm/tl-rtc-file-api
    env_file:
    - tlrtcfile.env
    environment:
    - tl_rtc_file_env_mode=http
    ports:
    - 9092:9092
    command: tlapi

  socket-http:
    profiles: ['http']
    container_name: socket
    image: iamtsm/tl-rtc-file-socket
    env_file:
    - tlrtcfile.env
    environment:
    - tl_rtc_file_env_mode=http
    ports:
    - 8444:8444
    command: tlsocket

  #https
  api-https:
    profiles: ['https']
    container_name: api
    image: iamtsm/tl-rtc-file-api
    env_file:
    - tlrtcfile.env
    environment:
    - tl_rtc_file_env_mode=https
    ports:
    - 9092:9092
    command: tlapi

  socket-https:
    profiles: ['https']
    container_name: socket
    image: iamtsm/tl-rtc-file-socket
    env_file:
    - tlrtcfile.env
    environment:
    - tl_rtc_file_env_mode=https
    ports:
    - 8444:8444
    command: tlsocket