## build the image from the Dockerfile in the current directory
## 1. 用于自己通过代码构建镜像
## 2. 用于推送到官方dockerhub

version: '3'
services:
  tl-rtc-file-api:
    env_file:
    - ../http.env
    environment:
      - tl_rtc_file_run_env=docker
    build: 
      context: ../
      dockerfile: docker/Dockerfile-build-code
    ports:
    - 9092:9092
    command: tlapi

  tl-rtc-file-socket:
    env_file:
    - ../http.env
    environment:
      - tl_rtc_file_run_env=docker
    build: 
      context: ../
      dockerfile: docker/Dockerfile-build-code
    ports:
    - 8444:8444
    command: tlsocket